[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.4.0-rc3" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.19.1" }
selene = {source = "kampfkarren/selene", version = "0.26.1"}
luau-lsp = {source="JohnnyMorganz/luau-lsp", version="1.27.0"}
wally = { source = "UpliftGames/wally", version = "0.3.2"}
wally-package-types = {source = "JohnnyMorganz/wally-package-types", version = "1.3.0"}